//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoMVC.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IServicePRoduct")]
    public interface IServicePRoduct {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePRoduct/GetProductos", ReplyAction="http://tempuri.org/IServicePRoduct/GetProductosResponse")]
        API.Models.Productos[] GetProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePRoduct/GetProductos", ReplyAction="http://tempuri.org/IServicePRoduct/GetProductosResponse")]
        System.Threading.Tasks.Task<API.Models.Productos[]> GetProductosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicePRoductChannel : KendoMVC.ServiceReference.IServicePRoduct, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePRoductClient : System.ServiceModel.ClientBase<KendoMVC.ServiceReference.IServicePRoduct>, KendoMVC.ServiceReference.IServicePRoduct {
        
        public ServicePRoductClient() {
        }
        
        public ServicePRoductClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePRoductClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePRoductClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePRoductClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public API.Models.Productos[] GetProductos() {
            return base.Channel.GetProductos();
        }
        
        public System.Threading.Tasks.Task<API.Models.Productos[]> GetProductosAsync() {
            return base.Channel.GetProductosAsync();
        }
    }
}
